<?php
Class CpeModel extends CI_Model
{
		public $TIPO_COMPROBANTE;
		public $EMISOR_RUC;
		public $EMISOR_RAZON_SOCIAL;
		public $EMISOR_NOMBRE_COMERCIAL;
		public $EMISOR_TIPO_DOCUMENTO_IDENTIDAD;
		public $EMISOR_COD_LOCAL_ANEXO;
		public $CLIENTE_TIPO_DOCUMENTO;
		public $CLIENTE_NUMERO_DOCUNENTO;
		public $CLIENTE_NOMBRE_RAZON_SOCIAL;
		public $CPE_TIPO_MONEDA;
		public $CPE_TIPO_OPERACION;
		public $CPE_SERIE_NUMERO;
		public $CPE_FECHA_EMISION;
		public $CPE_HORA;
		public $CPE_IMPORTE_TOTAL_TRIBUTOS;
		public $CPE_IMPORTE_GRAVADA_BASE_IMPONIBLE;
		public $CPE_IMPORTE_GRAVADA_VALOR_IGV;
		public $CPE_IMPORTE_EXPORTACIONES_SIN_IMPUESTOS;
		public $CPE_IMPORTE_INAFECTA_SIN_CARGOS;
		public $CPE_IMPORTE_EXONERADA;
		public $CPE_IMPORTE_GRATUITAS_TOTAL;
		public $CPE_IMPORTE_GRATUITAS_TOTAL_IGV;
		public $CPE_TOTAL_VALOR_VENTA;
		public $CPE_TOTAL_PRECIO_VENTA;
		public $CPE_TOTAL_OTROS_CARGOS;
		public $CPE_TOTAL_PAGAR;
		public $DETALLE;
}